### ISSUE TITLE
Update README with migration notes: simple decorator usage is broken after `NotConfiguredError` introducing

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#105]
## Broken example from the README (a little modified to show that this code does not work anymore)

```python
import asyncio
from cashews import cache

@cache(ttl=1)
async def long_running_function(foo):
    print("Hello")

asyncio.run(long_running_function(foo="bar"))
```
Error: `cashews.exceptions.NotConfiguredError: run `cache.setup(...)` before using cache`

## Versions
cashews 5.0.0
Python 3.10

## TODO

- [x] Fix decorators usage examples in the README
- [ ] Explain migration to 5.0.0 when only low-level API or a `@cache` decorator are required.

**Comment by AIGeneratedUsername** [comment]
I use `cashews.backends.redis.Redis` and `cashews.backends.redis.Memory` directly. I think I will need to put somewhere `Redis.setup()` and `Memory.setup()` just to make the package happy.

**Comment by Krukov** [comment]
Yep I think that we need to update code examples

**Comment by agcrum** [comment]
How should the decorator be used?

**Comment by Krukov** [comment]
@agcrum  Hi.  An example is next:
```python
import asyncio
from cashews import cache

cache.setup("mem://")

@cache(ttl=1)
async def long_running_function(foo):
    await asyncio.sleep(1)
    print(foo)


asyncio.run(long_running_function(foo="bar"))
asyncio.run(long_running_function(foo="bar"))
```
