### ISSUE TITLE
How to cache StreamingResponse/Generator?

### ISSUE THREAD

**Issue by mglowinski93** [Krukov/cashews#107]
Hi,
is that possible to cache generator with your library?

I'm trying to cache [StreamingResponse](https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse),
but this isn't trivial problem. Did you try to do something similar?

There is a couple of related issues with similar question (e.g. [here](https://github.com/tiangolo/fastapi/issues/4751)), but all of them are leading to [aiocache](https://github.com/aio-libs/aiocache).

**Comment by AIGeneratedUsername** [comment]
If you do not care about memory usage on your backend (because generators usually are used to use less memory when working with large objects), is not is simple to do not use a generator on your side?

**Comment by mglowinski93** [comment]
No, `StreamingResponse` requires `Async generator` to be passed as one parameters. I didn't find other option.

**Comment by Krukov** [comment]
@mglowinski93 Thanks for interesting case, I have never use cache with streaming  and there are a few problems with caching generators: they are stateful and hard to pickle (for redis storage). 
I can suggest one solution - is it use Object like Async generator:
```python
class FakeStreamer:
    def __init__(self):
        self._current = 0
        self._max = 10

    def __aiter__(self):
        return FakeStreamer()

    async def __anext__(self):
        self._current += 1
        if self._current == self._max:
            self._current = 0
            raise StopAsyncIteration
        return b"some fake video bytes"

    def __getstate__(self):
        state = self.__dict__.copy()
        state["_current"] = 0
        return state


@app.get("/stream")
@cache.cache(ttl="1h")
async def main():
    return StreamingResponse(FakeStreamer())
```
So here we use object as async generator because it is more easy to pickle and define __getstate__ also for pickle to drop the state + self._current = 0 on StopAsyncIteration drop the state if we store generator in memory cache. 

In general I do not recommend this workaround because we should be very careful with objects that have state.

And I have no idea how cashews can solve it, but I will think about it.

**Comment by mglowinski93** [comment]
Thank you @Krukov for an answer.

I agree, seems like proposed workaround is not a threadsafe.

Let's keep in touch, I will also investigate a topic further.

**Comment by AIGeneratedUsername** [comment]
> No, `StreamingResponse` requires `Async generator` to be passed as one parameters. I didn't find other option to use `StreamingResponse`.

I want to say that it looks like you do not need a `StreamingResponse` itself. Return a regular response. A client can stream your response.  See the example below.

> I have never use cache with streaming

If I am not wrong, caching all chunks of a generator will eat a similar amount of resources (memory) as if you convert a generator into something else.

---

I seems that the simplest solution is:
```python
from fastapi import FastAPI
from fastapi.testclient import TestClient

app = FastAPI()


async def fake_video_streamer():
    for i in range(10):
        yield b"some fake video bytes"


# @cache()  # Use any cache logic you want
async def fake_video_streamer_cached():
    return [_ async for _ in fake_video_streamer()]


@app.get("/foobar")
async def main():
    return await fake_video_streamer_cached()


client = TestClient(app)

def test_read_main():
    content = ""
    with client.stream("GET", "/foobar") as response:
        for chunk in response.iter_text():
            content += chunk
    assert response.status_code == 200
    assert "some fake video bytes" in content
```


---

If you nevertheless need to use a `StreamingResponse` for some reason that I am missing now, then you may think about caching at a much lower level, depending on when you get your data. E.g. cache your database calls, or (if you work with files) keep parts of files in memory, etc.

**Comment by mglowinski93** [comment]
@AIGeneratedUsername
Thank you for your tips.

Problem, which I'm facing is described [here](https://stackoverflow.com/questions/73671611/how-to-stream-html-content-with-static-files-using-fastapi), and based on that I need to use `StreamingResponse`.

Unfortunately, I can't cache on lower lever, since those services are not owned by me.

**Comment by mglowinski93** [comment]
@Krukov Did you maybe have time to investigate topic further :)?

**Comment by Krukov** [comment]
@mglowinski93  I have tried, but no succeed so far. The problem that `StreamingResponse` have async `interfaces` but pickle sync.  And for now I don't want to have some kind of hardcoded logic for any framework.  For my point of view cashews should provide interface like this 
```python
from cashews import cache

async def serializer(obj: StreamingResponse) -> bytes:
        data = b''
        async for chunk in obj.body_iterator:
            if not isinstance(chunk, bytes):
                chunk = chunk.encode(obj.charset)
            data += chunk
        return data

async def deserializer(value: bytes) -> Response:
      return Response(value)

cache.register_serialization(StreamingResponse, serializer, deserializer)
```

What do you think? Will this solve your problem?

**Comment by Krukov** [comment]
But it still not memory efficient 😞

**Comment by mglowinski93** [comment]
Moreover, we need to iterate over this twice. First time when returning `StreamingResponse` and second time while serializing the response.

Anyway, thanks for a feedback :)

**Comment by Krukov** [comment]
I think that I have an idea how to solve it. Let me try to make a PR, it will help me to explain it.

**Comment by Krukov** [comment]
I am here with a few solutions for you. 

The first that `cashews` can provide ASAP  - a decorator for async iterators
Implementation is [here ](https://github.com/Krukov/cashews/pull/125/files).  So to cache `StreamingResponse` you need to cache iterator itself instead of a whole handler: 
```python 
from cashews import cache

...

@cache.iterator(ttl="10m")
async def iterator():
    ...

@app.get("/stream")
async def stream():
    return StreamingResponse(iterator())

```

The second I want to release with the breaking changes, so it will be in 6.0 release soon. The idea is that I described here, but more generic ( and without doubling iteration) and the cashews will turn it on "automagiclly".  Implementation is [here ](https://github.com/Krukov/cashews/pull/123/files#diff-3df331569a7628a330e72e831d8f338342ef954c7cb3897c6195565a85c32b6fR1) and for user it will be simple 
```python 
from cashews import cache

...

async def iterator():
    ...

@app.get("/stream")
@cache(ttl="10m")
async def stream():
    return StreamingResponse(iterator())

```

I'm interested in your opinion on these options.

**Comment by mglowinski93** [comment]
Both solutions are acceptable for me, but second one seems a proper one. Good job!

**Comment by Krukov** [comment]
Yes, for now there are no limitation for size of caching data and an each chunk stored in a separate cache key. 
I think that with the decorator api it will be possible by [condition](https://github.com/Krukov/cashews#cache-condition) parameter ( I will add it )  .
```python 

from cashews import cache

...
def file_size_limit(result, args, kwargs, key):
    file_obj = kwargs["file_obj"]
    return file_size(file_obj) > 5 * MB

@cache.iterator(ttl="10m", condition=file_size_limit)
async def iterator(*, file_obj):
    ...

@app.get("/stream")
async def stream():
    return StreamingResponse(iterator())
```

So the usage depends on how your iterator looks like but I hope you get it. getting a file size is not an io operation so it shouldn't be a problem. I can give a full example if you need it.

**Comment by mglowinski93** [comment]
It would be great! BTW. I think similar example should be placed in `README.md` file :)

**Comment by Krukov** [comment]
Yes, good idea, but I will remake examples in a separate MR - for now It will live [here](https://github.com/Krukov/cashews/blob/8fb81ca97bb548587fd59cb657f06e1664751189/examples/fastapi_app.py#L27) 

Tomorrow I gonna to release 5.3.0 version with caching decorator for async iterators. stay tuned )

**Comment by mglowinski93** [comment]
I will!
Thanks a lot and good job:)

**Comment by Krukov** [comment]
Decorator released in 5.3.0

I already implemented new version that will handle StreamingResponse without headache, but it will released soon with a couple other backward incompatible changes. So I will keep this issue opened till this release

**Comment by mglowinski93** [comment]
Great, thanks.

**Comment by mglowinski93** [comment]
@Krukov 
To be clear, once https://github.com/Krukov/cashews/pull/123 is merged, there will be `6.0` release?

**Comment by Krukov** [comment]
Yes it is, but I think that it will happens in 2 weeks

**Comment by mglowinski93** [comment]
@Krukov
Sorry for the naughty questions, but there is some progress on this topic?

**Comment by Krukov** [comment]
yes sorry was busy a little . I gonna release it today or tomorrow

**Comment by mglowinski93** [comment]
@Krukov thank you!

**Comment by Krukov** [comment]
Released, please let me know if you will have any issues with it

**Comment by mglowinski93** [comment]
Thank you, seems to be working fine! Great job!
