### ISSUE TITLE
Does cashews need handle `IndexError` in `handle_message` in "redis/asyncio/client.py"?

### ISSUE THREAD

**Issue by simon-liebehenschel** [Krukov/cashews#162]
Maybe related:
- https://github.com/redis/redis-py/issues/1788
- https://github.com/redis/redis-py/issues/1490

I do not know how to reproduce this, but under some conditions the following can happen:
```py
"Task exception was never retrieved
future: <Task finished name='Task-9' coro=<BcastClientSide._listen_invalidate_forever() done, defined at /opt/pysetup/.venv/lib/python3.11/site-packages/cashews/backends/redis/client_side.py:94> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/cashews/backends/redis/client_side.py", line 97, in _listen_invalidate_forever
    await self._listen_invalidate()
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/cashews/backends/redis/client_side.py", line 122, in _listen_invalidate
    message = await channel.get_message(ignore_subscribe_messages=True, timeout=0.1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/redis/asyncio/client.py", line 971, in get_message
    return await self.handle_message(response, ignore_subscribe_messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/redis/asyncio/client.py", line 1011, in handle_message
    "data": response[2],
            ^^^^^^^^^^^
IndexError: list index out of range"
```

@Krukov Is it required to update https://github.com/Krukov/cashews/blob/e93d5a3bdad9c6af94b7838d5ac304bd3c35c47e/cashews/backends/redis/client_side.py#L122 with the following `try`/`except`:
```py
try:
    message = await channel.get_message(ignore_subscribe_messages=True, timeout=0.1)
except IndexError:
    continue
```
or cashews user should handle internal Redis/cashews exceptions on their side?

**Comment by Krukov** [comment]
Hi @AIGeneratedUsername 

What redis-py version do you have? 
5.0 version was released 2 month and I saw that they have some changes in `handle_message` (`get_message`)  so maybe  a new bug was introduced in the new version or (and more likely) they fixed this bug in 5.0

**Comment by Krukov** [comment]
Unfortunately we cant just ignore this Exception because it could be a message that should change a state of local cache ( it may lead to data inconsistency). So current behavior is expected and cashews users can't easily control this behavior.

**Comment by Krukov** [comment]
Can I close this issue ?
