### ISSUE TITLE
Unable to disable cache by providing "enable=0" or "disable=1" in cache setup

### ISSUE THREAD

**Issue by shijo-keyvalue** [Krukov/cashews#166]
As per documentation , we should be able to disable caching by providing "enable=0" or "disable=1" in cache setup.

I have tried doing both as given below , but the caching is not getting disabled.

`cache.setup("redis://0.0.0.0/?db=1&socket_connect_timeout=0.5&suppress=0&hash_key=my_secret&enable=0")`

`cache.setup("redis://0.0.0.0/?db=1&socket_connect_timeout=0.5&suppress=0&hash_key=my_secret&disable=1")`

@Krukov Can you please check.

**Comment by TR-items** [comment]
This is only from memory but i believe disabling works when set as param,

e.g. :
 `cache.setup("redis://0.0.0.0/?db=1&socket_connect_timeout=0.5&suppress=0&hash_key=my_secret",enable=False)`
`cache.setup("redis://0.0.0.0/?db=1&socket_connect_timeout=0.5&suppress=0&hash_key=my_secret",disable=True)`

So maybe try if the following does work:

`cache.setup("redis://0.0.0.0/?db=1&socket_connect_timeout=0.5&suppress=0&hash_key=my_secret&disable=True")`

**Comment by Krukov** [comment]
Hello @shijo-keyvalue 
I checked and it works as expected
```python
import asyncio
from random import randint

from cashews import cache

@cache(ttl="10m")
async def random():
    return randint(0, 100)

async def main():
    cache.setup("redis://0.0.0.0/?enable=1")

    print(await cache.set("key", 1))  # True
    print(await cache.get("key"))  # 1
    print(await random())  # 22

    cache.setup("redis://0.0.0.0/?enable=0")

    print(await cache.set("key", 1))  # None
    print(await cache.get("key"))  # None
    print(await random())  # 63



if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by Krukov** [comment]
Please reopen in case the issue still exist
