### ISSUE TITLE
Provision to skip caching immediately if not able to make connection with Redis

### ISSUE THREAD

**Issue by shijo-keyvalue** [Krukov/cashews#177]
Hi , when its unable to connect to redis using the connections parameters provided , API is taking around 20 seconds before it skips caching.
Is there any way in which we can reduce the time taken before caching is getting skipped ?
I have a requirement to immediately skip the cache if redis connection cannot be established.

I have tried this. But it didn't worked.

`cache.setup(redis_connection_url,retry_on_timeout=False, socket_connect_timeout=0.1)`

Any insights or recommendations on how to address this would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by olk-m** [comment]
Thank you for opening an issue, but I would move this to "Discussions".

You need to include more details.

> API is taking around 20 seconds before it skips caching

How do you know this? Can you show a small code sample and logs or an error traceback?

Please try to use `suppress=False` and show the error you get when "not able to make connection with Redis".

**Comment by Krukov** [comment]
Probably it is related to[ the bug with redis-p==5.0.1 ](https://github.com/redis/redis-py/pull/2997) 

What version of redis-py do you use?

**Comment by shijo-keyvalue** [comment]
@Krukov 
Yes , the version I was using was 5.0.1 . Now I changed it to 5.0.0.
Now its not taking 20 seconds to skip caching. Its getting completed in 1 second or so.
Please feel free to close if there is already another issue to track the same.

**Comment by Krukov** [comment]
Awesome. The issue is already [solved ](https://github.com/Krukov/cashews/blob/5294557e3179bc3ab683f7c3426ea0c7bee8744d/setup.cfg#L44)
