### ISSUE TITLE
Support soft ttl

### ISSUE THREAD

**Issue by cancan101** [Krukov/cashews#18]
along the lines of: https://github.com/aio-libs/aiocache/issues/256

and as a use case: when the cached operation has a transient failure (for example when fetching data from a 3rd party). In this case I may want to return the prior value if it is within a more generous ttl.

As an example:
```python
cached_value, age = read_from_cache(key)

if cached_value and age < ttl_soft:
   return cached_value

try:
   new_value = expensive_operation(key)
   save_cache(new_value, now)
   return new_value
except ex:
   if age < ttl:
      return cached_value
   raise ex
```

**Comment by Krukov** [comment]
Yes good case and I can suggest 2 solutions.


1. use 1 key for regular cache and another one with bigger ttl for failure case 
```python
from cashews import cache

@cache.failover(ttl="2d", key="{key}")
@cache(ttl="1h", key="+{key}")
async def expensive_operation(key):
    ...

```
In this way you will have 2 keys: 
- `fail:key` with ttl 2 days that will used if `expensive_operation` raise Exception ( will set only if expensive_operation executed)
- `key` with ttl 1 hour for cache

It will work a little bit different regarding your example 
```python
cached_value, age = read_from_cache(cache_key)

if cached_value and age < cache_key_ttl:
   return cached_value

try:
   new_value = expensive_operation(key)
   save_cache(new_value, now+cache_key_ttl, cache_key)
   save_cache(new_value, now+failure_key_ttl, failure_key)
   return new_value
except ex:
   cached_value, age = read_from_cache(failure_key)
   if age < failure_key_ttl:
      return cached_value
   raise ex
```

2. use cache decorator with some kind of soft ttl
```python
from cashews import cache

@cache.early(ttl="2d", early_ttl="1m", key="{key}")
async def expensive_operation(key):
    ...
```
Here we have one key for cache, that store a second ttl itself and try to recalculate `expensive_operation` if this ttl (early_ttl) is over. 
But there is a bug: if recalculation end up with error it will **not** try to recalculate it again. I will fix it asap

**Comment by cancan101** [comment]
If I understand how the `early_ttl` works, then that will actually happen in the background rather than blocking on that. i.e. the first time I call the cached function, if the amount of time is > early_ttl but < ttl, it will just return the current value and then kick of an async recalculation.

**Comment by Krukov** [comment]
@cancan101  yes right

**Comment by Krukov** [comment]
Hi  @cancan101 
I have a news - at release 3.2.0 `@cache.early` was fixed  and now if a error was happened during recalculation, it will try again with a next call.

**Comment by cancan101** [comment]
Thanks for the update! That being said there is still no way of doing option 2 but blocking until  there is a failure to recalculate? Ie not returning immediately with the potentially stale value and then doing the recirculation in the background but instead doing the recalculation in the foreground and then only using the stale value if there is failure?

**Comment by Krukov** [comment]
@cancan101  Yes there is no way to do it with only one key, but you can do it with 2 key like I wrote before:
```python
@cache.failover(ttl="2d", key="{key}")
@cache(ttl="1h", key="+{key}")
async def expensive_operation(key):
    ...
```

Is it make sense?

**Comment by Krukov** [comment]
Yes, I will reopen this issue for future improvements.

You right about downsides. Also I can offer to use in-memory cache for failure, of course with own cons:
```python
cache.setup("redis://0.0.0.0/")
cache.setup("mem://", prefix="fail:mem")

@cache.failover(ttl="2d", key="{key}", prefix="fail:mem")
@cache(ttl="1m", key="{key}")
async def expensive_operation(key):
    ...
```

**Comment by Krukov** [comment]
Hello, 

Sense 4.2.0 cashews have the strategy that we discussed - https://github.com/Krukov/cashews#soft
