### ISSUE TITLE
Migration of aiocache RedLock

### ISSUE THREAD

**Issue by rkrell** [Krukov/cashews#20]
Hello,

thanks for this great maintained library. I'm migrating my code from _aiocache_, which appears to be no longer maintained,

I just stumbled upon the implementation of the Redlock:

Former _aiocache_ implementation:

```python
async with RedLock(cache, key, lease=LEASE_LOCK_FUNC_CACHE):
    result = await cache.get(key)
    if result is not None:
        # Reset TTL on existing key
        await cache.expire(key, ttl=EXPIRE_FUNC_CACHE)
        # After a minimum waiting time resent answer to
        # repeating request
        logging.debug(
            '%s (%s): Cache hit, subsequently sending answer',
            subj_str, body)
        return bytes.fromhex(result)

    logging.debug('%s (%s): Cache missed, first call of message '
                  'handler', subj_str, body)
    result = await handler_class.answer(body)
    await cache.set(key, result.hex(), ttl=EXPIRE_FUNC_CACHE)
    return result
```

Comparable _cashews_ implementation:

```python
async with cache.lock(key + '-lock', expire=LEASE_LOCK_FUNC_CACHE):
    result = await cache.get(key)
    if result is not None:
        # Reset TTL on existing key
        await cache.expire(key, timeout=EXPIRE_FUNC_CACHE)
        # After a minimum waiting time resent answer to
        # repeating request
        logging.debug(
            '%s (%s): Cache hit, subsequently sending answer',
            subj_str, body)
        return bytes.fromhex(result)

    logging.debug('%s (%s): Cache missed, first call of message '
                  'handler', subj_str, body)
    result = await handler_class.answer(body)
    await cache.set(key, result.hex(), expire=EXPIRE_FUNC_CACHE)
    return result
```

Thus, for the `key` which is assembled from the function name and its arguments, for example, I need to add the suffix `-lock` for the lock key to not interfer with the key itself. The Redlock in _aiocache_ added this suffix implicitly, see https://github.com/aio-libs/aiocache/blob/9c8b07fe759990dcb2d4d5f4e40d13d2cc36d58f/aiocache/lock.py#L68.

Most probably this changed behavior is wanted, I just wanted to ask, whether you wanted to implement it in this way, and to point this out for anybody else migrating from _aiocache_.

**Comment by Krukov** [comment]
Hello,

Nice point and I think we can change current implementation of `cache.lock` contextmanager by adding the suffix. Sounds reasonable.

**Comment by rkrell** [comment]
Thank you, it really depends on what the lock is used for.
It maybe also sufficient to mention it in the documentation of add an inherited class Redlock, resulting in a call like this:

```python
async with cache.redlock(key', expire=LEASE_LOCK_FUNC_CACHE):
...
```

The library can be more or less "opinionated" regarding this.

**Comment by rkrell** [comment]
To be most flexible I'd leave the current behavior for users to be flexible with the key and keep it compatible, because not everybody uses it like above.
Best would be to max the regular lock a redlock by some customizing. One approach is explicitly adding the `'-lock'` prefix.

**Comment by Krukov** [comment]
Thanks for an idea and I have some points:
1. To be honest it is not a full redlock, because aiocache and cashews implements only a single instance approach and do not have implementation for a multi-master redis (https://redis.io/topics/distlock#the-redlock-algorithm). So name it  a `redlock` can confuse someone.
2. I think we can change current behavior, just because this context manager is a sugar for use lock and library is not so popular to worry about compatible. We can simply give a way to change a suffix:
```python
@asynccontextmanager
async def lock(self, key, expire, prefix="-lock"):
    ...
    
```
3. Would you like to contribute to fix it ?

**Comment by Krukov** [comment]
Oh, I just realized that avtosuffix can lead some misunderstanding and bugs, because cashews also provide `is_locked` function and in next case we will have unclear behavior 
```python
async with cache.lock(key, expire=LEASE_LOCK_FUNC_CACHE):
    print(cache.is_locked(key))
    
>>> False
```

**Comment by rkrell** [comment]
Yes, I don't believe static string defaults are the right way. Maybe this issue is enough documentation for users who should have the need of migrating from aiochache's "Redlock".

Also the note regarding the multi-master Redis (most probably for cloud solutions) is important.

For my purposes, this is sufficient. We use only a single master instance of Redis in the cloud.

**Comment by rkrell** [comment]
From my point of view this issue can be used as documentation and closed.
Thanks for the discussion.

**Comment by Krukov** [comment]
Thanks for the discussion too.
