### ISSUE TITLE
Unhandled exception when there are only backends with prefixes

### ISSUE THREAD

**Issue by sergey-burkov-trailstone** [Krukov/cashews#229]
+-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/contrib/fastapi.py", line 72, in dispatch
    |     with context, max_age(cache_control_value), self._cache.detect as detector:
    |   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    |     return next(self.gen)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/wrapper/disable_control.py", line 36, in disabling
    |     self.disable(*cmds, prefix=prefix)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/wrapper/disable_control.py", line 29, in disable
    |     return self._get_backend(prefix).disable(*cmds)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/wrapper/wrapper.py", line 41, in _get_backend
    |     backend, _ = self._get_backend_and_config(key)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/wrapper/transaction.py", line 36, in _get_backend_and_config
    |     backend, config = super()._get_backend_and_config(key)
    |   File "/home/sburkov/.virtualenvs/tscs-v2/lib/python3.10/site-packages/cashews/wrapper/wrapper.py", line 38, in _get_backend_and_config
    |     raise NotConfiguredError("Backend for given key not configured")
    | cashews.exceptions.NotConfiguredError: Backend for given key not configured

_Originally posted by @sergey-burkov-trailstone in https://github.com/Krukov/cashews/issues/218#issuecomment-2114598910_

**Comment by sergey-burkov-trailstone** [comment]
The exception is occurring by using CacheRequestControlMiddleware and  CacheDeleteMiddleware.
CacheEtagMiddleware is not configured/used.

**Comment by Krukov** [comment]
Was fixed in 7.2.0
