### ISSUE TITLE
Interrupted `StreamingResponse` will cache partial response

### ISSUE THREAD

**Issue by zoltan-fedor** [Krukov/cashews#246]
Great implementation of the caching of `StreamingResponse` for FastAPI (see https://github.com/Krukov/cashews/issues/107)!
It works really well for most scenarios.

Unfortunately I have discovered a scenario where it fails - when the stream is interrupted before it could finish, in which case it will cache only the partial response and  will server that partial response to all future requests.

This is happening because the `StreamingResponse` generator caches each 'event' generated as a separate `chunk` into Redis (basically a separate object) and nothing marks whether the generator got properly exhausted or not.
So if for any reason the generator doesn't finish (let's say because the client disappeared or cancelled the streaming request or the generator has errored out for any reason), then the chunks that are already cached are kept in the cache and served up for the next request.

This results in the incomplete generator events to be cached and served up for all future requests until the TTL is reached.

I guess the way to work around it would be if there could be an additional object saved into Redis when the generator has been properly exhausted, so when the next request comes in the cache loading could check whether that object representing the successful completion of the generator is there or not and if not, then it would know that the cached generator events are incomplete, so they are not to be used.

EDIT: Also, the `condition = NOT_NONE` doesn't seem to apply for when the `StreamingResponse` is interrupted before the first event could have been returned from the generator (which is a special case of the interrupted `StreamingResponse` where I have hoping that the `condition = NOT_NONE` might help)

**Comment by Krukov** [comment]
Hi @zoltan-fedor . Thanks for reporting this issue.

I'm sorry for making you wait so long, I have checked  all the things), it was a bug.  

I have done a fix the same as we have in `iterator` decorator and the same as you described. I. will release a new version soon.

**Comment by Krukov** [comment]
Was fixed in 7.2.0

**Comment by zoltan-fedor** [comment]
Thanks for fixing it.
Unfortunately now it seems it is not caching at all - even when the stream has completed.

I will need to dive into this to see what is going on now.
