### ISSUE TITLE
Add `noself=True` parameter (equivalent to "aiocache" package)

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#25]
[Source code for aiocache.decorators](https://aiocache.readthedocs.io/en/latest/_modules/aiocache/decorators.html?highlight=noself#)
```
    :param noself: bool if you are decorating a class function, by default self is also used to
        generate the key. This will result in same function calls done by different class instances
        to use different cache keys. Use noself=True if you want to ignore it.
```

**Comment by Krukov** [comment]
thanks, nice feature! Will add it soon.

**Comment by Krukov** [comment]
Hello, I have the PR for this feature, but I doubt. 

One think that I don't like in aiocache that key building is not obvious and hard. Especially if I want to play with the arguments and kwargs. That why in cashews a key is a template. 
So in this case more right way is using a key template:

```python
class MyObject:
    ...
    
    @cache(key="MyObject.my_method:{arg}", ttl="1h")  # like noself=True - like a global cache
    def my_method(self, arg):
        ...

    @cache(key="MyObject.other_method:id:{self.id}:{arg}", ttl="1h")  # like noself=False, but more smart then a generated key
    def other_method(self, arg):
        ...
``` 

@AIGeneratedUsername Is a key template more clear/convenient?

**Comment by AIGeneratedUsername** [comment]
A real use case is decorating dozens of methods with different parameters. I never even thought about key builder customizing. I was always happy to just pass `noself=True` and copy/paste decorator over many files.

My main question: is your idea scalable for large projects? In other words, will it be possible to exclude `self` without hard-coding parameters into a string?

```python
class Foo:
    
    @cache(exclude_first_parameter=True)   # Keep other args/kwargs as usually
    def(
        foo,
        bar,
        spam,
        *,
        eggs=None,
        abcdef=123456,
    ):
    ...
```

**Comment by Krukov** [comment]
Yes I got some, but some of them related to a fail cache:
```python

@cache.failover(key="last_articles")
async def get_last_articles(language):
     ...

```

Another example with template usage if using cache for entire handler that always have a `request` as argument
```python

@cache(ttl=timedelta(hours=2), key="margin:today")
async def get_margin_today(request):
    ...
    
@cache.dynamic(ttl=timedelta(days=2), key="accounts:{request.user.uid}")
async def accounts(request: Request) -> dict:
     ...

```

> My main question: is your idea scalable for large projects? In other words, will it be possible to exclude self without hard-coding parameters into a string?

 No, but to be honest to is not self if you name it foo ), but option named `noself`. But I got you point - I'll fix it.

**Comment by AIGeneratedUsername** [comment]
Sorry, I made a typo in my example. Of course, I wanted to write `self` as a first parameter. 

Anyway, you already understood the proposal.

**Comment by unmade** [comment]
Hey, @AIGeneratedUsername 

I don't understand how a `noself` parameter helps you with:

> decorating dozens of methods with different parameters.

It seems like you already can copy-paste `@cache()` and use auto-key generation.

However, If you want to for different class instances to use different cache keys it can achieved by using simple composition:

```python
def noself(deco):
    def outer(func):
        def inner(self, *args, **kwargs):
            return deco(func)(*args, **kwargs)
        return inner
    return outer


class SampleClass:
   
    @noself(cache(ttl="1h"))
    def(
        self,
        *args,
        **kwargs,
    ):
        ...
```

**Comment by Krukov** [comment]
I did research and I found an issue why this parameter was added to aiocache - aio-libs/aiocache#129 - nothing special, I mean that the there are no reason why method that need to be cached use self , but self is not used in value that will be in cache - it should be static or class method.

I have no doubt that it is useful for existing code, so I suggest that we can add workaround that @unmade made and put it to the documentation. We will have:
 ```python
 from cashews import cache, noself
 
 
 class SampleClass:
   
    @noself(cache(ttl="1h"))
    async def(
        self,
        *args,
        **kwargs,
    ):
        ...
 
 ```

**Comment by AIGeneratedUsername** [comment]
@unmade Could you please fix your example? I would be happy to do so, but I did not get your idea how your are going to cut off `self` and keep things working. Here is a sample (broken) code with your example:
```python
import asyncio
from functools import partial, wraps

from cashews import cache

cache.setup("mem://")


def noself(deco):
    def outer(method):
        def inner(self, *args, **kwargs):
            bound_method = wraps(method)(partial(method.__get__(self, type(self))))
            return deco(bound_method)(*args, **kwargs)

        return inner

    return outer


class SampleClass:

    @noself(cache(ttl="1h"))
    async def sample_method(self, spam, foo="bar"):
        print(f"{spam}; {foo}")


async def main():
    class_ = SampleClass()
    await class_.sample_method("eggs", foo="bar")

asyncio.run(main())
```

**Comment by AIGeneratedUsername** [comment]
In my own code, I wrote a decorator from the scratch, and I use inside it:
```python
            if noself:
                args = (type(args[0]), *args[1:])
           cache_key = get_cache_key(func, _key_template, args, kwargs)
```

**Comment by Krukov** [comment]
@unmade  @AIGeneratedUsername  The problem with `noself` decorator on cashews side because there is bug with partial functions. I'll fix it in mr soon

**Comment by Krukov** [comment]
@AIGeneratedUsername So I remade the decorator that @unmade suggested and we will have the next solution
```python
from cashews import cache, noself
class MyClass:
    @noself(cache)(ttl="2h")
    async def get_name(self, user, version="v1"):
         ...
```

I described this in the documentation, can you take a look on it in the MR ? As you see my english not so well - so any comments are welcome
