### ISSUE TITLE
RESP3 Support

### ISSUE THREAD

**Issue by TweedBeetle** [Krukov/cashews#275]
## Background
Cashews currently uses RESP2 (Redis Serialization Protocol version 2) for Redis connections. With the introduction of RESP3, which offers improved performance and new features, it would be nice if Cashews to supported this new protocol while maintaining backward compatibility with RESP2.

### Tasks
- Modify Redis connection setup to accept a `protocol_version` parameter
- Update Redis client initialization to use the specified protocol version
- Ensure compatibility with both RESP2 and RESP3 throughout the codebase
- Add unit tests for RESP3 functionality
- Update documentation to reflect new RESP3 support
- [Verify that all existing features work correctly with RESP3

### Files to Modify
- `/cashews/backends/redis/backend.py`
- `/cashews/backends/redis/__init__.py`
- `/cashews/backends/redis/client.py`
- `/cashews/backends/redis/client_side.py`
- `/setup.cfg`
- `README.md`

## References
- [Redis RESP3 Documentation](https://github.com/antirez/RESP3/blob/master/spec.md)
- [Redis-py RESP3 Support](https://redis-py.readthedocs.io/en/stable/resp3_features.html)

**Comment by alessio-locatelli** [comment]
You control all redis settings, including the `protocol` value:

```py
cache.setup(f"redis://{host}:{port}", protocol=3)
```

**Comment by TweedBeetle** [comment]
> You control all redis settings, including the `protocol` value:
> 
> ```python
> cache.setup(f"redis://{host}:{port}", protocol=3)
> ```

Ah thank you. Sorry i missed that!
