### ISSUE TITLE
docs: add a note that '@cache.locked' must be used in chain with '@cache'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#31]
Confusing, because someone may think that a result will be cached:
```python
@cache.locked(ttl="10m")
async def get(name):
    value = await api_call()
    return {"status": value}
```
I thought that the value will be cached until I've looked at the source code.

More clear example:
```python
@cache.locked(ttl="10m")
@cache(ttl="10m")
async def get(name):
    value = await api_call()
    return {"status": value}
```

I do not think that someone will install a caching package only to lock a function, so better to give a ready-to-use and not confusing example. What do you think?

Also, someone may want to write a custom decorator to avoid copy/pasting the same `ttl` over multiple decorators. E.g. `@cache(ttl="10m", lock=True)`.

**Comment by Krukov** [comment]
Thanks,  totally agree with you!

I don't really like functions with  many arguments,  so maybe we can have a shortcut  like `@locked_cache(ttl="10m")` ?

**Comment by AIGeneratedUsername** [comment]
Perhaps a shortcut (e.g. `@locked_cache(ttl="10m")`) may be more useful to mention in the first place. If someone needs more granular control or only locking, then `cache.locked` may be imported and used directly.

**Comment by Krukov** [comment]
So I decided to add the `lock` parameter  to the decorator

```python
@cache.cache(ttl=5, lock=True)
```
