### ISSUE TITLE
fix: wrong type hinting and redundant 'kwargs' in '_Redis.get()'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#37]
Wrong:

```python
class _Redis(Backend):

    async def get(self, key: str, **kwargs) -> Any:
        return await self._client.get(key, **kwargs)
```

Correct:
```python
class _Redis(Backend):

    async def get(self, key: str) -> bytes:
        return await self._client.get(key)
```

['Redis.key()' signature](https://aioredis.readthedocs.io/en/latest/api/high-level/#aioredis.client.Redis.get)

Problems:

1. `key()` does not accept `kwargs`
2. `key()` [always returns `bytes`](https://redis.io/commands/get)

---

By the way, not related to this issue, but `super().__init__()` is missing in `_Redis.__init__`.

**Comment by AIGeneratedUsername** [comment]
From the problem above, another questions appears. Since `get()` returns only `bytes`, do we need to handle `str` and `int` types here?

```python
class PickleSerializerMixin:

    def _process_value(self, value: Union[bytes, None, int, str], key, default=None):
```

**Comment by Krukov** [comment]
Thanks,  yes there are some `typing` problems here.

By the way `_Redis` implement the `Backend` interface and `get` should look like 
```python 
     async def get(self, key: str, default: Optional[Any] = None) -> Any:
```

**Comment by AIGeneratedUsername** [comment]
About type hinting. You write everywhere `Union[float, int]`, but this is redundant because `float` is the same. When you write `float`, it also says that `int` is accepted too. See https://www.python.org/dev/peps/pep-0484/#the-numeric-tower

**Comment by AIGeneratedUsername** [comment]
1. What do you think about updating to Python 3.10?
2. What do you think about updating and fixing (where required) all type hints?

If yes, for both Python 3.10 and type hints https://github.com/asottile/pyupgrade will be required. Of course, also Mypy will be required.

3. Are pull requests accepted?

**Comment by Krukov** [comment]
1. Of course we should do it
2. I think that library should care more about typehints for public interfaces - like decorators, and low level api  ( like `get`, `set` ... methods ), so yes . I don't know about [pyupgrade](https://github.com/asottile/pyupgrade) , but `mypy` should be added to ci pipelines (with soft config) 
3.  definitely yes, with a pleasure (I have small doubt about pyupgrade - looks like it is more for migration from 2.7)

**Comment by Krukov** [comment]
I have added python 3.10 support in https://github.com/Krukov/cashews/pull/52

**Comment by Krukov** [comment]
I'll close this issue. Some problems already fixed and some should be done with typing support  issue https://github.com/Krukov/cashews/issues/66
