### ISSUE TITLE
feat: migrate from 'aioredis-py' to 'redis-py'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#47]
[aioredis-py](https://github.com/aio-libs/aioredis-py) is moving now to the [redis-py](https://github.com/redis/redis-py)

Migration is not urgent and can be done within next year. I hope I will be less busy later and I will create a PR after 'redis-py' 4.2+ release.

I think I will create a PR for migration to Python 3.10 before that.

**Comment by Krukov** [comment]
wow, thanks for sharing this ) I didn't know about it.

PR is welcome

**Comment by Krukov** [comment]
I have add python 3.10 support n https://github.com/Krukov/cashews/pull/52

**Comment by AIGeneratedUsername** [comment]
Please review https://github.com/Krukov/cashews/pull/70
