### ISSUE TITLE
Method get() doesn't deserialize data after set_raw()

### ISSUE THREAD

**Issue by easysugar** [Krukov/cashews#59]
I'm expecting, that method get() deserialize raw pickle data stored in Redis, but it doesn't work in case of set_raw().

Code example:
```python
key = 'test:123'
value = [1, 2, 3]

# works fine
await cache.set(key, value)
print(await cache.get(key))
# [1, 2, 3]
print(await cache.get_raw(key))
# b':_\x80\x05\x95\x0b\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03e.'

# returns raw data
value2 = pickle.dumps(value)
await cache.set_raw(key, value2)
print(await cache.get(key))
# b'\x80\x04\x95\x0b\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03e.'
```

I see a difference in prefix `:_` - what does it mean?

**Comment by AIGeneratedUsername** [comment]
> I see a difference in prefix :_ - what does it mean?

Probably you are talking about this https://github.com/Krukov/cashews/blob/master/cashews/serialize.py#L89
```python
return await super().set(key, self._digestmod + b":" + sign + b"_" + value, *args, **kwargs)
```

---
>  but it doesn't work in case of set_raw().

Just wonder, what is a use case to use the `set_raw()` method if you want to use the `get()` method after that?

**Comment by easysugar** [comment]
OK, I got it.

> Just wonder, what is a use case

Actually, I do not use `set_raw()` in my code. Some of my keys in Redis are stored by another app (which doesn't use cashews) and I have to unpickle them too (what `get()` does already).

Currently my fix looks like this:
```python
value = await cache.get(key)
if value is None:
    return None
if isinstance(value, bytes):
    value = pickle.loads(value)
...
```

**Comment by Krukov** [comment]
Hello, yep as @AIGeneratedUsername  set != pickle + set_raw. Cashews also store in value meta information to check `hash`.  Also looks like this security feature is redundant so  maybe it will be removed soon )

**Comment by Krukov** [comment]
So I close this issue. Thanks
