### ISSUE TITLE
Add contributions guidelines and how to run tests

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#60]
For example, **pytest-cov** is not listed, but it is required. Could you please list all tests requirements?

**Comment by Krukov** [comment]
Hello, yes sorry.

-     pytest
-     pytest-asyncio
-     pytest-cov
-     aiohttp
-     fastapi
-     requests

I will fix dev requirements soon , In any problems with that you can check `tox.ini`

**Comment by Krukov** [comment]
Added some guide here https://github.com/Krukov/cashews#tests
