### ISSUE TITLE
size and key of in memory cache

### ISSUE THREAD

**Issue by liuzheyu1998** [Krukov/cashews#80]
Hi,

I wonder what is the unit of the size of in memory cache. For example, I used cache.setup("mem://") , while when I called the function 3 times with different arguments, it seems that all only previous 2 arguments are stored. 

In addition, I don't use any key as argument for the cache decorator, and I wonder if cashews will hash the function name and the arguments of the functions as the key?

Any feedback will be greatly appreciated.

**Comment by AIGeneratedUsername** [comment]
> when I called the function 3 times with different arguments, it seems that all only previous 2 arguments are stored.

Could you please include a reproducible code sample?


> I don't use any key as argument for the cache decorator, and I wonder if cashews will hash the function name and the arguments of the functions as the key?

Is `get_cache_key_template` and `generate_key_template` what you want to see: https://github.com/Krukov/cashews/blob/master/cashews/key.py#L51= ? Perhaps you did not see docstrings for both functions.

**Comment by Krukov** [comment]
@liuzheyu1998  Can I close the issue?

**Comment by Krukov** [comment]
Please reopen if you have questions
