### ISSUE TITLE
Implement set_many function

### ISSUE THREAD

**Issue by yashh** [Krukov/cashews#87]
I see that the package has a get_many which is very useful. However for a use case like get 50 user objects, we will need to set many users to cache at once. Can we implement it?

Decorator tip

```
@cache.list(key="user:{}", ttl="10m")
def get_users(ids: List[int]):
        ...
        return users
```

A decorator like this would be useful to cache multiple objects in one call. If you agree I can take a stab at pull request.

**Comment by AIGeneratedUsername** [comment]
I am +1 on this.
I think it makes sense to add such a function, because now In my code I need to inherit from cashews and define missing functionality:
```python
   async def multi_set(self, pairs: Mapping[AnyKeyT, EncodableT], *, ttl: int | None = None) -> None:
        async with self._client.pipeline(transaction=True) as pipe:
            pairs = {self._build_key(k): v for k, v in pairs.items()}  # type: ignore[misc]
            await pipe.mset(pairs)  # type: ignore[arg-type]
            if ttl:
                for key in pairs.keys():
                    await pipe.expire(key, ttl)
            await pipe.execute()
```

**Comment by Krukov** [comment]
Hi there. 

Yep, totally agreed with `set many`, but I have some doubts for the decorator. 
A first call it will set multi keys. It is easy, but what will happens if I call decorated function many times? Will It return cached results?

**Comment by yashh** [comment]
Thats right. The first call with set the multi keys while the subsequent would return from cache. The decorator would compute which of the keys are a hit, then compute the missing keys and then call the inner fn with the rest, set the cache and return. 

Anyway set_many would be sufficient.

**Comment by Krukov** [comment]
Got it. 
You are welcome to make a PR even with the decorator.  I will be glad

**Comment by yashh** [comment]
https://github.com/Krukov/cashews/compare/master...yashh:cashews:master

Could you guide me a bit here. I have a WIP set_many working. Since I am not using the `self._with_middlewares` function set_many is not created backend._client attribute yet. If I call get / get_many that will initiate the connection everything works as expected. Am I on the right path?

**Comment by Krukov** [comment]
You are right about `with_middlewares`, but you are not on a right way. The problem that Wrapper - it a place to work with multiply backends and execute middewares - it is a some kid of proxy class for others "backends".  And there are a few Backends: redis, memory and disk - they all are implementation of Backend interface.  So I think that you should define a new method `set_many` as a part of [backend interface ](https://github.com/Krukov/cashews/blob/master/cashews/backends/interface.py). And all magic with a pipeline should be only in the [Redis backend](https://github.com/Krukov/cashews/blob/master/cashews/backends/redis/backend.py)

**Comment by yashh** [comment]
Take #2.
https://github.com/Krukov/cashews/compare/master...yashh:cashews:master

So I implemented set_many in redis, disk & memory backends. I see that redis-cli monitor is getting the right commands. However when I read the keys back with get_many right after set_many I get (None, None). I know redis is properly returning the right data. However 

```for _keys in backends.values():
            _values = await self._with_middlewares("get_many", _keys[0])(*_keys, default=default)
            result.update(dict(zip(_keys, _values)))```

_values is (None, None). Any idea what it could be?

**Comment by Krukov** [comment]
@yashh 
You on right way, LGFM. I think that the problem with `None`s related to a pickle serialization.To solve it you need to implement `set_many` in [PickleSerializerMixin](https://github.com/Krukov/cashews/blob/a0932dd4c866dbce8c6397da3a5bbbf049ba8a1c/cashews/serialize.py) and PickleSerializerMixin shouldn't know about Redis ). And to be honest I don't now how exactly you can implement it.

**Comment by yashh** [comment]
```
    async def set_many(self, pairs: Dict[str, Any], *args: Any, **kwargs: Any):
        data = {}
        for key, value in pairs.items():
            transformed_value = None
            if isinstance(value, int) and not isinstance(value, bool):
                transformed_value = pairs[key]
            else:
                transformed_value = self._pickler.dumps(value)
            data[key] = self._prepend_sign_to_value(key, transformed_value)
        return await super().set_many(data, *args, **kwargs)
```
Great. I implemented the `set_many` on the PickleSerializer and now `get_many` works!  I was able to store strings, objects and other types.

**Comment by Krukov** [comment]
Great !  Waiting for your PR )
