### ISSUE TITLE
Connecting Redis on Kubernetes with backend using cashews

### ISSUE THREAD

**Issue by liuzheyu1998** [Krukov/cashews#89]
Hi, thank you a lot for this repo, and I really appreciate it a lot. I have tried to use cashews with Redis on my local environment, and it works pretty well thanks to your previous assistance. 

Currently, I deployed both the Redis service and the application on separate Kubernetes containers, and I wonder if it is possible to use cashews on backend to get access to the Redis server on another Kubernetes container. Any feedback will be greatly appreciated.

**Comment by Krukov** [comment]
Hi, thank you too! 

Yes, you can use cashews with a redis on another container/host. You need only setup a redis uri in a right way:

```python
from cashews import cache

cache.setup("redis://redis.default.svc.cluster.local") # just an example
```
