### ISSUE TITLE
Enable "pre-commit" bot to bump linters versions automatically

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#96]
Homepage: https://github.com/marketplace/pre-commit-ci

Documentation: https://pre-commit.ci/

I think there is nothing I help with from my side, but this must be simple. Perhaps one-click installing of the bot is enough.

**UPD:** 

Here is an example for [auto-merging](https://github.com/aio-libs/aiojobs/commit/23da3b9f0ba78c31c4e3ae62c23b8d6802b5a5a4).

**Comment by Krukov** [comment]
I hope it is done
